version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - db
      
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "MyPassword001"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"