// <auto-generated />
using System;
using BC7.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BC7.Database.Migrations
{
    [DbContext(typeof(BitClub7Context))]
    [Migration("20190630194751_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BC7.Domain.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("BC7.Domain.MatrixPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("DepthLevel");

                    b.Property<int>("Left");

                    b.Property<int>("MatrixLevel");

                    b.Property<Guid?>("ParentId");

                    b.Property<int>("Right");

                    b.Property<Guid?>("UserMultiAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserMultiAccountId");

                    b.ToTable("MatrixPositions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a5af626-cf3d-40c7-b05b-94da55551fff"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1335),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 0,
                            Right = 30,
                            UserMultiAccountId = new Guid("f7283501-3c65-473f-b2c5-84b094c522a6")
                        },
                        new
                        {
                            Id = new Guid("3dfb5c5d-af7e-4df0-a332-04b2893d23ab"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1919),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 0,
                            ParentId = new Guid("5a5af626-cf3d-40c7-b05b-94da55551fff"),
                            Right = 15,
                            UserMultiAccountId = new Guid("2c06de2f-a710-4642-8903-ab6b7c57b5f5")
                        },
                        new
                        {
                            Id = new Guid("1acb5125-97e2-4fe8-85d8-aeb260640f5f"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1931),
                            DepthLevel = 1,
                            Left = 16,
                            MatrixLevel = 0,
                            ParentId = new Guid("5a5af626-cf3d-40c7-b05b-94da55551fff"),
                            Right = 29,
                            UserMultiAccountId = new Guid("ff63a56b-7de8-4746-8c79-6e775d53582b")
                        },
                        new
                        {
                            Id = new Guid("5cb0ee5a-e892-426b-b4a0-6eb8a68fff3f"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1934),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 0,
                            ParentId = new Guid("3dfb5c5d-af7e-4df0-a332-04b2893d23ab"),
                            Right = 8,
                            UserMultiAccountId = new Guid("eb8c3fa0-4fb9-47ce-bd7e-92f5976f1c64")
                        },
                        new
                        {
                            Id = new Guid("44247d80-7a01-4ba5-b7eb-91ea2fe9df86"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1936),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 0,
                            ParentId = new Guid("3dfb5c5d-af7e-4df0-a332-04b2893d23ab"),
                            Right = 14,
                            UserMultiAccountId = new Guid("20b2dad2-b2be-42af-af47-afd0e936634f")
                        },
                        new
                        {
                            Id = new Guid("27c9473f-77a4-4b8b-aba8-d4f974d0e864"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1939),
                            DepthLevel = 2,
                            Left = 17,
                            MatrixLevel = 0,
                            ParentId = new Guid("1acb5125-97e2-4fe8-85d8-aeb260640f5f"),
                            Right = 22,
                            UserMultiAccountId = new Guid("577e391c-df4e-42cc-a5f2-c0111e8d2c83")
                        },
                        new
                        {
                            Id = new Guid("ee94cf3e-199b-408e-a770-fa7f161e34f6"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1942),
                            DepthLevel = 2,
                            Left = 23,
                            MatrixLevel = 0,
                            ParentId = new Guid("1acb5125-97e2-4fe8-85d8-aeb260640f5f"),
                            Right = 28,
                            UserMultiAccountId = new Guid("ddf2f3ec-a989-418a-8460-2fbcb9281b1b")
                        },
                        new
                        {
                            Id = new Guid("7408a3e1-6f6f-49e6-8812-a4bccd1f2c9a"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1951),
                            DepthLevel = 3,
                            Left = 4,
                            MatrixLevel = 0,
                            ParentId = new Guid("5cb0ee5a-e892-426b-b4a0-6eb8a68fff3f"),
                            Right = 5
                        },
                        new
                        {
                            Id = new Guid("bca10fe3-59e3-4c89-9a9a-c2471e01bd27"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1951),
                            DepthLevel = 3,
                            Left = 6,
                            MatrixLevel = 0,
                            ParentId = new Guid("5cb0ee5a-e892-426b-b4a0-6eb8a68fff3f"),
                            Right = 7
                        },
                        new
                        {
                            Id = new Guid("9322fc0f-b204-4d52-a2f5-aefe556b6e77"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1954),
                            DepthLevel = 3,
                            Left = 10,
                            MatrixLevel = 0,
                            ParentId = new Guid("44247d80-7a01-4ba5-b7eb-91ea2fe9df86"),
                            Right = 11
                        },
                        new
                        {
                            Id = new Guid("2b5e23b5-cd92-48e3-bbab-fd1309de9612"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1957),
                            DepthLevel = 3,
                            Left = 12,
                            MatrixLevel = 0,
                            ParentId = new Guid("44247d80-7a01-4ba5-b7eb-91ea2fe9df86"),
                            Right = 13
                        },
                        new
                        {
                            Id = new Guid("8ef18845-399b-45e4-9f79-cd7ce9a51880"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1957),
                            DepthLevel = 3,
                            Left = 18,
                            MatrixLevel = 0,
                            ParentId = new Guid("27c9473f-77a4-4b8b-aba8-d4f974d0e864"),
                            Right = 19
                        },
                        new
                        {
                            Id = new Guid("98c6ce9e-6d37-4f79-84b5-6f72f3bffbf3"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1960),
                            DepthLevel = 3,
                            Left = 20,
                            MatrixLevel = 0,
                            ParentId = new Guid("27c9473f-77a4-4b8b-aba8-d4f974d0e864"),
                            Right = 21
                        },
                        new
                        {
                            Id = new Guid("984781d1-e1aa-4d3d-af82-376cd2807c8b"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1963),
                            DepthLevel = 3,
                            Left = 24,
                            MatrixLevel = 0,
                            ParentId = new Guid("ee94cf3e-199b-408e-a770-fa7f161e34f6"),
                            Right = 25
                        },
                        new
                        {
                            Id = new Guid("801965bd-e13b-4078-a1c2-d00002ce5570"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(1963),
                            DepthLevel = 3,
                            Left = 26,
                            MatrixLevel = 0,
                            ParentId = new Guid("ee94cf3e-199b-408e-a770-fa7f161e34f6"),
                            Right = 27
                        },
                        new
                        {
                            Id = new Guid("6ea13f12-4f0f-4efd-876e-78566edce08f"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2328),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 1,
                            Right = 14,
                            UserMultiAccountId = new Guid("f7283501-3c65-473f-b2c5-84b094c522a6")
                        },
                        new
                        {
                            Id = new Guid("e80dab1b-52fb-4a82-8597-b385ab6e9b07"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2331),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 1,
                            ParentId = new Guid("6ea13f12-4f0f-4efd-876e-78566edce08f"),
                            Right = 7,
                            UserMultiAccountId = new Guid("2c06de2f-a710-4642-8903-ab6b7c57b5f5")
                        },
                        new
                        {
                            Id = new Guid("5640c90b-70ea-41d9-a361-f2cddc9bbd9b"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2334),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 1,
                            ParentId = new Guid("6ea13f12-4f0f-4efd-876e-78566edce08f"),
                            Right = 13,
                            UserMultiAccountId = new Guid("ff63a56b-7de8-4746-8c79-6e775d53582b")
                        },
                        new
                        {
                            Id = new Guid("b435eef8-44f6-4145-9c5d-8a5761d4c877"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2337),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 1,
                            ParentId = new Guid("e80dab1b-52fb-4a82-8597-b385ab6e9b07"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("a464e75c-f6a5-4888-baba-92a6ba7f8a50"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2337),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 1,
                            ParentId = new Guid("e80dab1b-52fb-4a82-8597-b385ab6e9b07"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("ca744662-cf8e-4131-9ba0-52a575bc9de2"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2340),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 1,
                            ParentId = new Guid("5640c90b-70ea-41d9-a361-f2cddc9bbd9b"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("04a9e3ce-d632-4b3c-ae95-f163acad0957"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2340),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 1,
                            ParentId = new Guid("5640c90b-70ea-41d9-a361-f2cddc9bbd9b"),
                            Right = 12
                        },
                        new
                        {
                            Id = new Guid("cc3f900a-b2f4-4b6f-b6b2-caa17af265ca"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2369),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 2,
                            Right = 14,
                            UserMultiAccountId = new Guid("f7283501-3c65-473f-b2c5-84b094c522a6")
                        },
                        new
                        {
                            Id = new Guid("f31fc5a8-6f26-437f-8906-04d35caf90cf"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2378),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 2,
                            ParentId = new Guid("cc3f900a-b2f4-4b6f-b6b2-caa17af265ca"),
                            Right = 7,
                            UserMultiAccountId = new Guid("2c06de2f-a710-4642-8903-ab6b7c57b5f5")
                        },
                        new
                        {
                            Id = new Guid("7b400f63-441d-40cf-9bf9-00d55a6677b1"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2381),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 2,
                            ParentId = new Guid("cc3f900a-b2f4-4b6f-b6b2-caa17af265ca"),
                            Right = 13,
                            UserMultiAccountId = new Guid("ff63a56b-7de8-4746-8c79-6e775d53582b")
                        },
                        new
                        {
                            Id = new Guid("3e7095fd-8d15-42ad-b22c-499cc51bd0cc"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2381),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 2,
                            ParentId = new Guid("f31fc5a8-6f26-437f-8906-04d35caf90cf"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("43d4ad62-830e-4e27-a346-776e1f939de2"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2384),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 2,
                            ParentId = new Guid("f31fc5a8-6f26-437f-8906-04d35caf90cf"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("6b3b8b8b-c494-45ed-88eb-9792c334e213"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2387),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 2,
                            ParentId = new Guid("7b400f63-441d-40cf-9bf9-00d55a6677b1"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("afd2bf2c-06e5-4e39-80a1-c413f48a550b"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2390),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 2,
                            ParentId = new Guid("7b400f63-441d-40cf-9bf9-00d55a6677b1"),
                            Right = 12
                        },
                        new
                        {
                            Id = new Guid("8633e62c-f439-408c-b3a7-09b98e12077b"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2405),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 3,
                            Right = 14,
                            UserMultiAccountId = new Guid("f7283501-3c65-473f-b2c5-84b094c522a6")
                        },
                        new
                        {
                            Id = new Guid("9b22206e-ba7d-48a3-be72-26b7f6074db3"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2405),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 3,
                            ParentId = new Guid("8633e62c-f439-408c-b3a7-09b98e12077b"),
                            Right = 7,
                            UserMultiAccountId = new Guid("2c06de2f-a710-4642-8903-ab6b7c57b5f5")
                        },
                        new
                        {
                            Id = new Guid("33ff46a1-fb5d-4634-b5a5-86de8c84f6a1"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2413),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 3,
                            ParentId = new Guid("8633e62c-f439-408c-b3a7-09b98e12077b"),
                            Right = 13,
                            UserMultiAccountId = new Guid("ff63a56b-7de8-4746-8c79-6e775d53582b")
                        },
                        new
                        {
                            Id = new Guid("ab1bd571-25f4-4f09-8ce3-154c2df8efac"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2416),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 3,
                            ParentId = new Guid("9b22206e-ba7d-48a3-be72-26b7f6074db3"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("ffd650af-99a8-4103-b3d9-3b0c9682f4ba"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2416),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 3,
                            ParentId = new Guid("9b22206e-ba7d-48a3-be72-26b7f6074db3"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("69b6e0c1-1f3c-417d-b19a-40d617c43753"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2419),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 3,
                            ParentId = new Guid("33ff46a1-fb5d-4634-b5a5-86de8c84f6a1"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("46c9af90-3595-478e-9aba-f14aebc978be"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2422),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 3,
                            ParentId = new Guid("33ff46a1-fb5d-4634-b5a5-86de8c84f6a1"),
                            Right = 12
                        },
                        new
                        {
                            Id = new Guid("0df78f75-566f-4e02-87e2-8e030f1fb3c9"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2437),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 4,
                            Right = 14,
                            UserMultiAccountId = new Guid("f7283501-3c65-473f-b2c5-84b094c522a6")
                        },
                        new
                        {
                            Id = new Guid("443e45dd-eeea-4886-a72e-aae6f64b339f"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2437),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 4,
                            ParentId = new Guid("0df78f75-566f-4e02-87e2-8e030f1fb3c9"),
                            Right = 7,
                            UserMultiAccountId = new Guid("2c06de2f-a710-4642-8903-ab6b7c57b5f5")
                        },
                        new
                        {
                            Id = new Guid("6b09c107-e332-4245-be21-a43c3a4496fe"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2486),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 4,
                            ParentId = new Guid("0df78f75-566f-4e02-87e2-8e030f1fb3c9"),
                            Right = 13,
                            UserMultiAccountId = new Guid("ff63a56b-7de8-4746-8c79-6e775d53582b")
                        },
                        new
                        {
                            Id = new Guid("2dccbb21-75da-478c-9e50-0d66d207cbef"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2495),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 4,
                            ParentId = new Guid("443e45dd-eeea-4886-a72e-aae6f64b339f"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("7a502e73-5d16-4bd0-8946-f835761663f9"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2495),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 4,
                            ParentId = new Guid("443e45dd-eeea-4886-a72e-aae6f64b339f"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("20b76e7e-d8cf-4f0e-abae-d7f54015d121"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2498),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 4,
                            ParentId = new Guid("6b09c107-e332-4245-be21-a43c3a4496fe"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("9385719f-7be6-4f43-8ef0-8f865752ac54"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2501),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 4,
                            ParentId = new Guid("6b09c107-e332-4245-be21-a43c3a4496fe"),
                            Right = 12
                        },
                        new
                        {
                            Id = new Guid("907b592a-cc92-440c-a3d7-a851f0636023"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2516),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 5,
                            Right = 14,
                            UserMultiAccountId = new Guid("f7283501-3c65-473f-b2c5-84b094c522a6")
                        },
                        new
                        {
                            Id = new Guid("ae83af06-06fc-43c2-80b3-ef8deb73b689"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2519),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 5,
                            ParentId = new Guid("907b592a-cc92-440c-a3d7-a851f0636023"),
                            Right = 7,
                            UserMultiAccountId = new Guid("2c06de2f-a710-4642-8903-ab6b7c57b5f5")
                        },
                        new
                        {
                            Id = new Guid("8f17ca0f-3438-4f54-b42c-e4fb38599786"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2519),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 5,
                            ParentId = new Guid("907b592a-cc92-440c-a3d7-a851f0636023"),
                            Right = 13,
                            UserMultiAccountId = new Guid("ff63a56b-7de8-4746-8c79-6e775d53582b")
                        },
                        new
                        {
                            Id = new Guid("0a2949ca-6bf1-4a41-935d-06f40c258892"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2522),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 5,
                            ParentId = new Guid("ae83af06-06fc-43c2-80b3-ef8deb73b689"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("9b153ec7-5aee-4871-9872-4e047fd5263e"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2527),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 5,
                            ParentId = new Guid("ae83af06-06fc-43c2-80b3-ef8deb73b689"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("a463d564-63ab-4080-9f96-a87f6fbaac50"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2530),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 5,
                            ParentId = new Guid("8f17ca0f-3438-4f54-b42c-e4fb38599786"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("fc91662d-e282-4529-b9f5-0b4e968da928"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2530),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 5,
                            ParentId = new Guid("8f17ca0f-3438-4f54-b42c-e4fb38599786"),
                            Right = 12
                        },
                        new
                        {
                            Id = new Guid("559717ea-163a-4f88-bfea-cfdce35bdc29"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2545),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 6,
                            Right = 14,
                            UserMultiAccountId = new Guid("f7283501-3c65-473f-b2c5-84b094c522a6")
                        },
                        new
                        {
                            Id = new Guid("2da184da-69e7-430a-b303-2e478e55aeed"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2548),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 6,
                            ParentId = new Guid("559717ea-163a-4f88-bfea-cfdce35bdc29"),
                            Right = 7,
                            UserMultiAccountId = new Guid("2c06de2f-a710-4642-8903-ab6b7c57b5f5")
                        },
                        new
                        {
                            Id = new Guid("fdd7fca0-63d2-4fbc-aed3-066c81da3262"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2551),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 6,
                            ParentId = new Guid("559717ea-163a-4f88-bfea-cfdce35bdc29"),
                            Right = 13,
                            UserMultiAccountId = new Guid("ff63a56b-7de8-4746-8c79-6e775d53582b")
                        },
                        new
                        {
                            Id = new Guid("75e8f7b6-7a14-4323-9a7d-23909251d80d"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2554),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 6,
                            ParentId = new Guid("2da184da-69e7-430a-b303-2e478e55aeed"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("6c28d050-e499-4908-873a-24d69b717d19"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2557),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 6,
                            ParentId = new Guid("2da184da-69e7-430a-b303-2e478e55aeed"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("be45b1fc-8649-4ef6-9296-b6e785b21fb1"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2565),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 6,
                            ParentId = new Guid("fdd7fca0-63d2-4fbc-aed3-066c81da3262"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("c8456d59-f31a-426c-80e6-d45274f505d5"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 88, DateTimeKind.Utc).AddTicks(2568),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 6,
                            ParentId = new Guid("fdd7fca0-63d2-4fbc-aed3-066c81da3262"),
                            Right = 12
                        });
                });

            modelBuilder.Entity("BC7.Domain.PaymentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AmountToPay")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("OrderId");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("PaymentFor")
                        .IsRequired();

                    b.Property<Guid>("PaymentId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("PaymentHistories");
                });

            modelBuilder.Entity("BC7.Domain.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FullTicketNumber");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Subject")
                        .IsRequired();

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BC7.Domain.UserAccountData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BtcWalletAddress")
                        .IsRequired();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Hash")
                        .IsRequired();

                    b.Property<bool>("IsMembershipFeePaid");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Role")
                        .IsRequired();

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.Property<string>("Street")
                        .IsRequired();

                    b.Property<string>("ZipCode")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("UserAccountsData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d89d7a45-91f4-4347-8b65-f46cf61dbe5d"),
                            BtcWalletAddress = "BtcWalletAddressRoot",
                            City = "CityRoot",
                            Country = "CountryRoot",
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 50, 971, DateTimeKind.Utc).AddTicks(8397),
                            Email = "root@bitclub7.com",
                            FirstName = "FirstNameRoot",
                            Hash = "Sc8cdO+purS95CSscawE5gUtZ1n2073wEcExUdlFJvyykbZ8MrmB9JATz4p/gHK5IKb2QdZCdLxiwV1NmvE5haDHbD+G51OPBOxq5Bx9C9nwgdXtm+8gohkPvK+SyDtPIUiazZGsbiMP9GItdff8Tx1sgf0CqBw3s1WOsfPxZB7kCa6oLGlfME4pqiNiH12z4tO56iaDWmzxqV7wfRpJ1VwvNBFY+MCCLoRQVKQTRokrjZr7kV9V5fSqGOMUoM+ZfoxKEboMJdkQN5DKnuzE+/HaSVqKxrn0Y2DCCrwJLGmqdkeQSh4C4FJsyl39K/iuIC0bVohUOhdcxlSNOfW/GA==",
                            IsMembershipFeePaid = true,
                            LastName = "LastNameRoot",
                            Login = "root",
                            Role = "Root",
                            Salt = "MtJ8oklAP5Q=",
                            Street = "StreetRoot",
                            ZipCode = "ZipCodeRoot"
                        },
                        new
                        {
                            Id = new Guid("0de42c7f-bc1c-4734-9a95-14ae590073b3"),
                            BtcWalletAddress = "BtcWalletAddressAdmin",
                            City = "CityAdmin",
                            Country = "CountryAdmin",
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 31, DateTimeKind.Utc).AddTicks(3611),
                            Email = "admin@bitclub7.com",
                            FirstName = "FirstNameAdmin",
                            Hash = "QoI0a3MYeg/G8onsLCVElQfdy7byynXnpBs/GFWbDdFlz3Tnhecywq+ejsnBBgn3O/zOaJVDugVc4iGOV5t4ovOo7Vkqzuw5GpC+u82p1Hob19O+mjtk7g5gTzyyJnI3an+DuHZxC7Y4CWhO0/zVjLsxu5Fsi6s/dsLxdqVn2gx9wkf7T8dLQrzQWDwmuAP/zUcym7NMvbptat+dPxIH5nKq6r8QWwsQPFSuFYWsH7rrKtzRwYK2Y/1kZOlGrTyH+/tYlJnp9GCFMWch7fTX39fn4NA34sw9HHWhLGeRmGACsz5OXPuaESv0NqtabglJeU1js/U2jB38dScMyC5kKg==",
                            IsMembershipFeePaid = true,
                            LastName = "LastNameAdmin",
                            Login = "admin",
                            Role = "Admin",
                            Salt = "a8sYtCTk5eY=",
                            Street = "StreetAdmin",
                            ZipCode = "ZipCodeAdmin"
                        });
                });

            modelBuilder.Entity("BC7.Domain.UserMultiAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("IsMainAccount");

                    b.Property<string>("MultiAccountName");

                    b.Property<string>("RefLink");

                    b.Property<Guid?>("SponsorId");

                    b.Property<Guid>("UserAccountDataId");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.HasIndex("UserAccountDataId");

                    b.ToTable("UserMultiAccounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7283501-3c65-473f-b2c5-84b094c522a6"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 87, DateTimeKind.Utc).AddTicks(2203),
                            IsMainAccount = true,
                            MultiAccountName = "root-001",
                            UserAccountDataId = new Guid("d89d7a45-91f4-4347-8b65-f46cf61dbe5d")
                        },
                        new
                        {
                            Id = new Guid("2c06de2f-a710-4642-8903-ab6b7c57b5f5"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 87, DateTimeKind.Utc).AddTicks(3728),
                            IsMainAccount = false,
                            MultiAccountName = "root-002",
                            UserAccountDataId = new Guid("d89d7a45-91f4-4347-8b65-f46cf61dbe5d")
                        },
                        new
                        {
                            Id = new Guid("ff63a56b-7de8-4746-8c79-6e775d53582b"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 87, DateTimeKind.Utc).AddTicks(3739),
                            IsMainAccount = false,
                            MultiAccountName = "root-003",
                            UserAccountDataId = new Guid("d89d7a45-91f4-4347-8b65-f46cf61dbe5d")
                        },
                        new
                        {
                            Id = new Guid("eb8c3fa0-4fb9-47ce-bd7e-92f5976f1c64"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 87, DateTimeKind.Utc).AddTicks(3742),
                            IsMainAccount = true,
                            MultiAccountName = "admin-001",
                            UserAccountDataId = new Guid("0de42c7f-bc1c-4734-9a95-14ae590073b3")
                        },
                        new
                        {
                            Id = new Guid("20b2dad2-b2be-42af-af47-afd0e936634f"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 87, DateTimeKind.Utc).AddTicks(3751),
                            IsMainAccount = false,
                            MultiAccountName = "admin-002",
                            UserAccountDataId = new Guid("0de42c7f-bc1c-4734-9a95-14ae590073b3")
                        },
                        new
                        {
                            Id = new Guid("577e391c-df4e-42cc-a5f2-c0111e8d2c83"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 87, DateTimeKind.Utc).AddTicks(3754),
                            IsMainAccount = false,
                            MultiAccountName = "admin-003",
                            UserAccountDataId = new Guid("0de42c7f-bc1c-4734-9a95-14ae590073b3")
                        },
                        new
                        {
                            Id = new Guid("ddf2f3ec-a989-418a-8460-2fbcb9281b1b"),
                            CreatedAt = new DateTime(2019, 6, 30, 19, 47, 51, 87, DateTimeKind.Utc).AddTicks(3763),
                            IsMainAccount = false,
                            MultiAccountName = "admin-004",
                            UserAccountDataId = new Guid("0de42c7f-bc1c-4734-9a95-14ae590073b3")
                        });
                });

            modelBuilder.Entity("Z.EntityFramework.Plus.AuditEntry", b =>
                {
                    b.Property<int>("AuditEntryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("EntitySetName")
                        .HasMaxLength(255);

                    b.Property<string>("EntityTypeName")
                        .HasMaxLength(255);

                    b.Property<int>("State");

                    b.Property<string>("StateName")
                        .HasMaxLength(255);

                    b.HasKey("AuditEntryID");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Z.EntityFramework.Plus.AuditEntryProperty", b =>
                {
                    b.Property<int>("AuditEntryPropertyID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditEntryID");

                    b.Property<string>("NewValueFormatted")
                        .HasColumnName("NewValue");

                    b.Property<string>("OldValueFormatted")
                        .HasColumnName("OldValue");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(255);

                    b.Property<string>("RelationName")
                        .HasMaxLength(255);

                    b.HasKey("AuditEntryPropertyID");

                    b.HasIndex("AuditEntryID");

                    b.ToTable("AuditEntryProperties");
                });

            modelBuilder.Entity("BC7.Domain.Article", b =>
                {
                    b.HasOne("BC7.Domain.UserAccountData", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BC7.Domain.MatrixPosition", b =>
                {
                    b.HasOne("BC7.Domain.UserMultiAccount")
                        .WithMany("MatrixPositions")
                        .HasForeignKey("UserMultiAccountId");
                });

            modelBuilder.Entity("BC7.Domain.UserMultiAccount", b =>
                {
                    b.HasOne("BC7.Domain.UserMultiAccount", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId");

                    b.HasOne("BC7.Domain.UserAccountData", "UserAccountData")
                        .WithMany("UserMultiAccounts")
                        .HasForeignKey("UserAccountDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Z.EntityFramework.Plus.AuditEntryProperty", b =>
                {
                    b.HasOne("Z.EntityFramework.Plus.AuditEntry", "Parent")
                        .WithMany("Properties")
                        .HasForeignKey("AuditEntryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
