// <auto-generated />
using System;
using BC7.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BC7.Database.Migrations
{
    [DbContext(typeof(BitClub7Context))]
    [Migration("20190701133858_InitDatabase")]
    partial class InitDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BC7.Domain.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatorId");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("BC7.Domain.MatrixPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("DepthLevel");

                    b.Property<int>("Left");

                    b.Property<int>("MatrixLevel");

                    b.Property<Guid?>("ParentId");

                    b.Property<int>("Right");

                    b.Property<Guid?>("UserMultiAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserMultiAccountId");

                    b.ToTable("MatrixPositions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f85b8f04-5d1f-4261-bf8b-626c1bdd392c"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(1911),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 0,
                            Right = 30,
                            UserMultiAccountId = new Guid("441c799c-e2b7-4f1c-b141-db3c6c1af034")
                        },
                        new
                        {
                            Id = new Guid("2bde30b3-599a-4e41-b820-9dc589937071"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2818),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 0,
                            ParentId = new Guid("f85b8f04-5d1f-4261-bf8b-626c1bdd392c"),
                            Right = 15,
                            UserMultiAccountId = new Guid("c1b6ef5c-6e70-4982-bca3-f5407d1e431e")
                        },
                        new
                        {
                            Id = new Guid("93f69513-67b1-4c34-befa-e81707335d35"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2877),
                            DepthLevel = 1,
                            Left = 16,
                            MatrixLevel = 0,
                            ParentId = new Guid("f85b8f04-5d1f-4261-bf8b-626c1bdd392c"),
                            Right = 29,
                            UserMultiAccountId = new Guid("975ec706-0f87-4c21-adbf-215f0b36d5cf")
                        },
                        new
                        {
                            Id = new Guid("4d87f944-4a53-4431-abee-0a64e1d8a0f4"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2880),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 0,
                            ParentId = new Guid("2bde30b3-599a-4e41-b820-9dc589937071"),
                            Right = 8,
                            UserMultiAccountId = new Guid("bde6962c-a69f-4070-b9c7-d5a3c5421a6e")
                        },
                        new
                        {
                            Id = new Guid("9bfba368-c480-48d0-b8a5-7669af6123fe"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2882),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 0,
                            ParentId = new Guid("2bde30b3-599a-4e41-b820-9dc589937071"),
                            Right = 14,
                            UserMultiAccountId = new Guid("6d1d38db-8f4d-48c8-af76-7bc5e50b1cb1")
                        },
                        new
                        {
                            Id = new Guid("00f8f3ec-f9cf-478b-b3d1-2a338cd35054"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2885),
                            DepthLevel = 2,
                            Left = 17,
                            MatrixLevel = 0,
                            ParentId = new Guid("93f69513-67b1-4c34-befa-e81707335d35"),
                            Right = 22,
                            UserMultiAccountId = new Guid("f5d34aaa-455b-4be0-8d77-7017ee3ffde5")
                        },
                        new
                        {
                            Id = new Guid("2e8d71f8-24a4-48ac-8088-12b1351327cf"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2894),
                            DepthLevel = 2,
                            Left = 23,
                            MatrixLevel = 0,
                            ParentId = new Guid("93f69513-67b1-4c34-befa-e81707335d35"),
                            Right = 28,
                            UserMultiAccountId = new Guid("e374d579-ef95-46ab-99b9-c947a0eb62de")
                        },
                        new
                        {
                            Id = new Guid("2daf2a6f-7cec-4ff3-b15d-5c8356031d04"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2897),
                            DepthLevel = 3,
                            Left = 4,
                            MatrixLevel = 0,
                            ParentId = new Guid("4d87f944-4a53-4431-abee-0a64e1d8a0f4"),
                            Right = 5
                        },
                        new
                        {
                            Id = new Guid("f52b3c6f-bfba-4090-bc8d-7bc0f04dc87a"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2900),
                            DepthLevel = 3,
                            Left = 6,
                            MatrixLevel = 0,
                            ParentId = new Guid("4d87f944-4a53-4431-abee-0a64e1d8a0f4"),
                            Right = 7
                        },
                        new
                        {
                            Id = new Guid("438ebaf1-9835-46ed-b37b-4abe905848c1"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2900),
                            DepthLevel = 3,
                            Left = 10,
                            MatrixLevel = 0,
                            ParentId = new Guid("9bfba368-c480-48d0-b8a5-7669af6123fe"),
                            Right = 11
                        },
                        new
                        {
                            Id = new Guid("ec2bacb3-fa9a-46eb-a998-5c1218ae8aab"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2903),
                            DepthLevel = 3,
                            Left = 12,
                            MatrixLevel = 0,
                            ParentId = new Guid("9bfba368-c480-48d0-b8a5-7669af6123fe"),
                            Right = 13
                        },
                        new
                        {
                            Id = new Guid("43d3a359-e00e-4379-9e89-671da81e7a1e"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2906),
                            DepthLevel = 3,
                            Left = 18,
                            MatrixLevel = 0,
                            ParentId = new Guid("00f8f3ec-f9cf-478b-b3d1-2a338cd35054"),
                            Right = 19
                        },
                        new
                        {
                            Id = new Guid("c4c58868-ef2d-4c2e-b6d3-db48d46cdd5d"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2906),
                            DepthLevel = 3,
                            Left = 20,
                            MatrixLevel = 0,
                            ParentId = new Guid("00f8f3ec-f9cf-478b-b3d1-2a338cd35054"),
                            Right = 21
                        },
                        new
                        {
                            Id = new Guid("06a52c28-e984-4a93-bac8-8f515480a2ac"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2909),
                            DepthLevel = 3,
                            Left = 24,
                            MatrixLevel = 0,
                            ParentId = new Guid("2e8d71f8-24a4-48ac-8088-12b1351327cf"),
                            Right = 25
                        },
                        new
                        {
                            Id = new Guid("b2e1041f-26a7-4b65-9ada-908f16ff53f7"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(2915),
                            DepthLevel = 3,
                            Left = 26,
                            MatrixLevel = 0,
                            ParentId = new Guid("2e8d71f8-24a4-48ac-8088-12b1351327cf"),
                            Right = 27
                        },
                        new
                        {
                            Id = new Guid("de35ee8e-5217-41f3-9902-407b082d5c7a"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3234),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 1,
                            Right = 14,
                            UserMultiAccountId = new Guid("441c799c-e2b7-4f1c-b141-db3c6c1af034")
                        },
                        new
                        {
                            Id = new Guid("0dacc2f1-c2b2-42aa-95bc-cc090ac0781e"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3236),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 1,
                            ParentId = new Guid("de35ee8e-5217-41f3-9902-407b082d5c7a"),
                            Right = 7,
                            UserMultiAccountId = new Guid("c1b6ef5c-6e70-4982-bca3-f5407d1e431e")
                        },
                        new
                        {
                            Id = new Guid("a50347be-ef95-47cc-8001-d65120945ae1"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3239),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 1,
                            ParentId = new Guid("de35ee8e-5217-41f3-9902-407b082d5c7a"),
                            Right = 13,
                            UserMultiAccountId = new Guid("975ec706-0f87-4c21-adbf-215f0b36d5cf")
                        },
                        new
                        {
                            Id = new Guid("0dd4a5b4-136b-4d67-ae2e-9cc0b0e86426"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3239),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 1,
                            ParentId = new Guid("0dacc2f1-c2b2-42aa-95bc-cc090ac0781e"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("20847eaf-a4ae-47a4-9ca1-11666c52ed5e"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3242),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 1,
                            ParentId = new Guid("0dacc2f1-c2b2-42aa-95bc-cc090ac0781e"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("d24790ea-aad8-45e0-9bdf-32095094c072"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3245),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 1,
                            ParentId = new Guid("a50347be-ef95-47cc-8001-d65120945ae1"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("f3c6bc8a-cac9-4cc2-832b-fe7621c32e70"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3245),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 1,
                            ParentId = new Guid("a50347be-ef95-47cc-8001-d65120945ae1"),
                            Right = 12
                        },
                        new
                        {
                            Id = new Guid("50ac185b-e596-4469-9b84-af83420e6bc0"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3280),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 2,
                            Right = 14,
                            UserMultiAccountId = new Guid("441c799c-e2b7-4f1c-b141-db3c6c1af034")
                        },
                        new
                        {
                            Id = new Guid("cacc8dcc-711a-4527-a95b-eb8704d92572"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3283),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 2,
                            ParentId = new Guid("50ac185b-e596-4469-9b84-af83420e6bc0"),
                            Right = 7,
                            UserMultiAccountId = new Guid("c1b6ef5c-6e70-4982-bca3-f5407d1e431e")
                        },
                        new
                        {
                            Id = new Guid("b298bd5e-cca8-4c88-accc-cb9daebbac43"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3286),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 2,
                            ParentId = new Guid("50ac185b-e596-4469-9b84-af83420e6bc0"),
                            Right = 13,
                            UserMultiAccountId = new Guid("975ec706-0f87-4c21-adbf-215f0b36d5cf")
                        },
                        new
                        {
                            Id = new Guid("bbf68af4-33bd-4141-9d52-70577a056416"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3289),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 2,
                            ParentId = new Guid("cacc8dcc-711a-4527-a95b-eb8704d92572"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("ef6af0b3-4efd-431a-96c9-7951db8ff4ee"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3289),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 2,
                            ParentId = new Guid("cacc8dcc-711a-4527-a95b-eb8704d92572"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("aea0c28c-8733-48fb-8cdd-e96c776ba543"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3292),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 2,
                            ParentId = new Guid("b298bd5e-cca8-4c88-accc-cb9daebbac43"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("77492f5f-da59-4b08-b732-ac902827d8d6"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3295),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 2,
                            ParentId = new Guid("b298bd5e-cca8-4c88-accc-cb9daebbac43"),
                            Right = 12
                        },
                        new
                        {
                            Id = new Guid("55b831a0-fede-4d1d-b1de-afb300331242"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3310),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 3,
                            Right = 14,
                            UserMultiAccountId = new Guid("441c799c-e2b7-4f1c-b141-db3c6c1af034")
                        },
                        new
                        {
                            Id = new Guid("cc96d0e4-74c8-4752-a330-989939af3579"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3318),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 3,
                            ParentId = new Guid("55b831a0-fede-4d1d-b1de-afb300331242"),
                            Right = 7,
                            UserMultiAccountId = new Guid("c1b6ef5c-6e70-4982-bca3-f5407d1e431e")
                        },
                        new
                        {
                            Id = new Guid("98c5b782-a1d8-49cb-99b1-d98c9900b8ad"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3318),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 3,
                            ParentId = new Guid("55b831a0-fede-4d1d-b1de-afb300331242"),
                            Right = 13,
                            UserMultiAccountId = new Guid("975ec706-0f87-4c21-adbf-215f0b36d5cf")
                        },
                        new
                        {
                            Id = new Guid("5c3a20e3-334b-4020-a1d1-2bc2257a8938"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3321),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 3,
                            ParentId = new Guid("cc96d0e4-74c8-4752-a330-989939af3579"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("ba73bbb5-0d9d-4f56-9ee3-94450e4c3824"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3324),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 3,
                            ParentId = new Guid("cc96d0e4-74c8-4752-a330-989939af3579"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("8a3a8474-1233-4621-b7ba-2c4570518135"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3324),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 3,
                            ParentId = new Guid("98c5b782-a1d8-49cb-99b1-d98c9900b8ad"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("928f6f4f-d6b7-4f7f-a791-efa9152078e9"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3327),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 3,
                            ParentId = new Guid("98c5b782-a1d8-49cb-99b1-d98c9900b8ad"),
                            Right = 12
                        },
                        new
                        {
                            Id = new Guid("b147e664-c083-4110-8aeb-b54e78365aa1"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3342),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 4,
                            Right = 14,
                            UserMultiAccountId = new Guid("441c799c-e2b7-4f1c-b141-db3c6c1af034")
                        },
                        new
                        {
                            Id = new Guid("2036142b-541f-4124-b09d-b1b39c2c1ba0"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3342),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 4,
                            ParentId = new Guid("b147e664-c083-4110-8aeb-b54e78365aa1"),
                            Right = 7,
                            UserMultiAccountId = new Guid("c1b6ef5c-6e70-4982-bca3-f5407d1e431e")
                        },
                        new
                        {
                            Id = new Guid("1babc389-43c0-4e1f-9506-f251e6372b17"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3351),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 4,
                            ParentId = new Guid("b147e664-c083-4110-8aeb-b54e78365aa1"),
                            Right = 13,
                            UserMultiAccountId = new Guid("975ec706-0f87-4c21-adbf-215f0b36d5cf")
                        },
                        new
                        {
                            Id = new Guid("29a74bb5-013e-40a1-8b7a-58b7b11dd398"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3354),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 4,
                            ParentId = new Guid("2036142b-541f-4124-b09d-b1b39c2c1ba0"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("2fd26ed3-c8e8-455d-ad71-cd1952b889ee"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3354),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 4,
                            ParentId = new Guid("2036142b-541f-4124-b09d-b1b39c2c1ba0"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("cd62fe7d-c451-4df7-8a8c-3d69a7ef51a8"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3356),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 4,
                            ParentId = new Guid("1babc389-43c0-4e1f-9506-f251e6372b17"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("ad847c40-882a-410c-8b07-6458dc1f33b3"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3359),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 4,
                            ParentId = new Guid("1babc389-43c0-4e1f-9506-f251e6372b17"),
                            Right = 12
                        },
                        new
                        {
                            Id = new Guid("89cf4d81-0226-401e-9a49-8b1211caf441"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3371),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 5,
                            Right = 14,
                            UserMultiAccountId = new Guid("441c799c-e2b7-4f1c-b141-db3c6c1af034")
                        },
                        new
                        {
                            Id = new Guid("e82a3015-3bd5-4664-aac1-32090e2091a9"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3374),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 5,
                            ParentId = new Guid("89cf4d81-0226-401e-9a49-8b1211caf441"),
                            Right = 7,
                            UserMultiAccountId = new Guid("c1b6ef5c-6e70-4982-bca3-f5407d1e431e")
                        },
                        new
                        {
                            Id = new Guid("1b2c7f23-962c-43e3-9367-54df4f17b7e0"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3377),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 5,
                            ParentId = new Guid("89cf4d81-0226-401e-9a49-8b1211caf441"),
                            Right = 13,
                            UserMultiAccountId = new Guid("975ec706-0f87-4c21-adbf-215f0b36d5cf")
                        },
                        new
                        {
                            Id = new Guid("f3e5b60f-cd06-4a88-98fa-8fff6e17b346"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3383),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 5,
                            ParentId = new Guid("e82a3015-3bd5-4664-aac1-32090e2091a9"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("9a348e77-da5e-4f09-bda8-5cb0555eea2e"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3386),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 5,
                            ParentId = new Guid("e82a3015-3bd5-4664-aac1-32090e2091a9"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("607cc017-54e8-478a-9ef5-e92278aa870a"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3386),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 5,
                            ParentId = new Guid("1b2c7f23-962c-43e3-9367-54df4f17b7e0"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("2672defa-e166-4c9b-b9b4-6b559473143b"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3389),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 5,
                            ParentId = new Guid("1b2c7f23-962c-43e3-9367-54df4f17b7e0"),
                            Right = 12
                        },
                        new
                        {
                            Id = new Guid("b3bcc637-b794-4263-8ef5-e29c4f222a04"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3400),
                            DepthLevel = 0,
                            Left = 1,
                            MatrixLevel = 6,
                            Right = 14,
                            UserMultiAccountId = new Guid("441c799c-e2b7-4f1c-b141-db3c6c1af034")
                        },
                        new
                        {
                            Id = new Guid("70b21a08-2d7c-4afe-9dc1-79e365880cd7"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3403),
                            DepthLevel = 1,
                            Left = 2,
                            MatrixLevel = 6,
                            ParentId = new Guid("b3bcc637-b794-4263-8ef5-e29c4f222a04"),
                            Right = 7,
                            UserMultiAccountId = new Guid("c1b6ef5c-6e70-4982-bca3-f5407d1e431e")
                        },
                        new
                        {
                            Id = new Guid("0191e80e-66e7-49da-ad48-0ae26717c0aa"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3403),
                            DepthLevel = 1,
                            Left = 8,
                            MatrixLevel = 6,
                            ParentId = new Guid("b3bcc637-b794-4263-8ef5-e29c4f222a04"),
                            Right = 13,
                            UserMultiAccountId = new Guid("975ec706-0f87-4c21-adbf-215f0b36d5cf")
                        },
                        new
                        {
                            Id = new Guid("fbe104b5-364d-435f-b7c3-c79a6b013cd8"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3406),
                            DepthLevel = 2,
                            Left = 3,
                            MatrixLevel = 6,
                            ParentId = new Guid("70b21a08-2d7c-4afe-9dc1-79e365880cd7"),
                            Right = 4
                        },
                        new
                        {
                            Id = new Guid("868c959a-3d3b-4f98-9ad1-1afdcbc3e692"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3441),
                            DepthLevel = 2,
                            Left = 5,
                            MatrixLevel = 6,
                            ParentId = new Guid("70b21a08-2d7c-4afe-9dc1-79e365880cd7"),
                            Right = 6
                        },
                        new
                        {
                            Id = new Guid("f7b96740-38c7-4c18-8172-13e350b783fc"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3444),
                            DepthLevel = 2,
                            Left = 9,
                            MatrixLevel = 6,
                            ParentId = new Guid("0191e80e-66e7-49da-ad48-0ae26717c0aa"),
                            Right = 10
                        },
                        new
                        {
                            Id = new Guid("7d871840-f354-4ec8-be1c-86958874c70f"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 105, DateTimeKind.Utc).AddTicks(3444),
                            DepthLevel = 2,
                            Left = 11,
                            MatrixLevel = 6,
                            ParentId = new Guid("0191e80e-66e7-49da-ad48-0ae26717c0aa"),
                            Right = 12
                        });
                });

            modelBuilder.Entity("BC7.Domain.PaymentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AmountToPay")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("OrderId");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("PaymentFor")
                        .IsRequired();

                    b.Property<Guid>("PaymentId");

                    b.Property<string>("Status")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("PaymentHistories");
                });

            modelBuilder.Entity("BC7.Domain.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FullTicketNumber");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Subject")
                        .IsRequired();

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BC7.Domain.UserAccountData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BtcWalletAddress")
                        .IsRequired();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Hash")
                        .IsRequired();

                    b.Property<bool>("IsMembershipFeePaid");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Role")
                        .IsRequired();

                    b.Property<string>("Salt")
                        .IsRequired();

                    b.Property<string>("Street")
                        .IsRequired();

                    b.Property<string>("ZipCode")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("UserAccountsData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("870a7b28-8564-4b0d-9190-054381e29c94"),
                            BtcWalletAddress = "BtcWalletAddressRoot",
                            City = "CityRoot",
                            Country = "CountryRoot",
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 57, 989, DateTimeKind.Utc).AddTicks(4320),
                            Email = "root@bitclub7.com",
                            FirstName = "FirstNameRoot",
                            Hash = "RTZC5gPA3PvU1wh5v8OZcU0CDxUAA+ULZ5QPK+UF2D7BoBGsiZNZTFEP9TL9jCGEsMkHFWZne6YpQGoZQcl2oFFy6DsHIaliyP3BOdGlzlp1XnhN4tnNakD9ExU3hM/6tKtOzhlWAiRsrNAU6wbNKrKofWKTMx9VM1sPsHKUoICWuZuio/BQJLV4ShApxL1MNssD5pTsHZMiIar7H5IEkJyndiXTEEVOcQnUF09KCIEjAOzsqOSv8Z1fPkDc6QXyIRKSHcOiVyS0ZdRaoCjpofvPc5zBAnqA2K/cHIjliIeTdYwQXAltOIKU2Xnr6lxKiE5OhO3B0VVaYvUw9S5Fvw==",
                            IsMembershipFeePaid = true,
                            LastName = "LastNameRoot",
                            Login = "root",
                            Role = "Root",
                            Salt = "VQHv7XzASWI=",
                            Street = "StreetRoot",
                            ZipCode = "ZipCodeRoot"
                        },
                        new
                        {
                            Id = new Guid("b34995c4-8a31-49df-81cc-66159918700d"),
                            BtcWalletAddress = "BtcWalletAddressAdmin",
                            City = "CityAdmin",
                            Country = "CountryAdmin",
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 48, DateTimeKind.Utc).AddTicks(3918),
                            Email = "admin@bitclub7.com",
                            FirstName = "FirstNameAdmin",
                            Hash = "jvGNNvIDW80tDzgGFlJV6xzxgPYtDm4CyX3wbIiv7lTBG8otFDXYjcVZ9kx7ArwkO6SMQ7L3JxZyrhb/EKtGPEV0oAQEm6owUXBCBO+aS+8+6h4soVel4ynY+uQMCWTvzbzdDOjj4jBhkBwzJB+kbvGwDolP4WLTRhKNvYJNuEUZFxZs4f6alqjJWjIWu9EY/IjmJWp4MXl78Qer7Wou7OUyOE7A/vh3Au/4zVN2aqd3Zz1xQL7elvmTKze3jAE0lNxH63OHrTySq6MSdPQv87Atodl2QMx5ZyXEzhA4mupk6PToWWPU1ddR9noEBbCHCgaj9dB6rZI86vBuhA8CcA==",
                            IsMembershipFeePaid = true,
                            LastName = "LastNameAdmin",
                            Login = "admin",
                            Role = "Admin",
                            Salt = "0jG6iqjmF+0=",
                            Street = "StreetAdmin",
                            ZipCode = "ZipCodeAdmin"
                        });
                });

            modelBuilder.Entity("BC7.Domain.UserMultiAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("IsMainAccount");

                    b.Property<string>("MultiAccountName");

                    b.Property<string>("RefLink");

                    b.Property<Guid?>("SponsorId");

                    b.Property<Guid>("UserAccountDataId");

                    b.HasKey("Id");

                    b.HasIndex("SponsorId");

                    b.HasIndex("UserAccountDataId");

                    b.ToTable("UserMultiAccounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("441c799c-e2b7-4f1c-b141-db3c6c1af034"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 104, DateTimeKind.Utc).AddTicks(866),
                            IsMainAccount = true,
                            MultiAccountName = "root-001",
                            UserAccountDataId = new Guid("870a7b28-8564-4b0d-9190-054381e29c94")
                        },
                        new
                        {
                            Id = new Guid("c1b6ef5c-6e70-4982-bca3-f5407d1e431e"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 104, DateTimeKind.Utc).AddTicks(3292),
                            IsMainAccount = false,
                            MultiAccountName = "root-002",
                            UserAccountDataId = new Guid("870a7b28-8564-4b0d-9190-054381e29c94")
                        },
                        new
                        {
                            Id = new Guid("975ec706-0f87-4c21-adbf-215f0b36d5cf"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 104, DateTimeKind.Utc).AddTicks(3303),
                            IsMainAccount = false,
                            MultiAccountName = "root-003",
                            UserAccountDataId = new Guid("870a7b28-8564-4b0d-9190-054381e29c94")
                        },
                        new
                        {
                            Id = new Guid("bde6962c-a69f-4070-b9c7-d5a3c5421a6e"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 104, DateTimeKind.Utc).AddTicks(3306),
                            IsMainAccount = true,
                            MultiAccountName = "admin-001",
                            RefLink = "xm3dgjTbckuxSfk0",
                            UserAccountDataId = new Guid("b34995c4-8a31-49df-81cc-66159918700d")
                        },
                        new
                        {
                            Id = new Guid("6d1d38db-8f4d-48c8-af76-7bc5e50b1cb1"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 104, DateTimeKind.Utc).AddTicks(4778),
                            IsMainAccount = false,
                            MultiAccountName = "admin-002",
                            RefLink = "CbJGE3bl65zWhUwK",
                            UserAccountDataId = new Guid("b34995c4-8a31-49df-81cc-66159918700d")
                        },
                        new
                        {
                            Id = new Guid("f5d34aaa-455b-4be0-8d77-7017ee3ffde5"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 104, DateTimeKind.Utc).AddTicks(4796),
                            IsMainAccount = false,
                            MultiAccountName = "admin-003",
                            RefLink = "nB1Mw99LCQuKXUY2",
                            UserAccountDataId = new Guid("b34995c4-8a31-49df-81cc-66159918700d")
                        },
                        new
                        {
                            Id = new Guid("e374d579-ef95-46ab-99b9-c947a0eb62de"),
                            CreatedAt = new DateTime(2019, 7, 1, 13, 38, 58, 104, DateTimeKind.Utc).AddTicks(4799),
                            IsMainAccount = false,
                            MultiAccountName = "admin-004",
                            RefLink = "2ERrHKzmA7bigBeY",
                            UserAccountDataId = new Guid("b34995c4-8a31-49df-81cc-66159918700d")
                        });
                });

            modelBuilder.Entity("Z.EntityFramework.Plus.AuditEntry", b =>
                {
                    b.Property<int>("AuditEntryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("EntitySetName")
                        .HasMaxLength(255);

                    b.Property<string>("EntityTypeName")
                        .HasMaxLength(255);

                    b.Property<int>("State");

                    b.Property<string>("StateName")
                        .HasMaxLength(255);

                    b.HasKey("AuditEntryID");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Z.EntityFramework.Plus.AuditEntryProperty", b =>
                {
                    b.Property<int>("AuditEntryPropertyID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditEntryID");

                    b.Property<string>("NewValueFormatted")
                        .HasColumnName("NewValue");

                    b.Property<string>("OldValueFormatted")
                        .HasColumnName("OldValue");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(255);

                    b.Property<string>("RelationName")
                        .HasMaxLength(255);

                    b.HasKey("AuditEntryPropertyID");

                    b.HasIndex("AuditEntryID");

                    b.ToTable("AuditEntryProperties");
                });

            modelBuilder.Entity("BC7.Domain.Article", b =>
                {
                    b.HasOne("BC7.Domain.UserAccountData", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BC7.Domain.MatrixPosition", b =>
                {
                    b.HasOne("BC7.Domain.UserMultiAccount")
                        .WithMany("MatrixPositions")
                        .HasForeignKey("UserMultiAccountId");
                });

            modelBuilder.Entity("BC7.Domain.UserMultiAccount", b =>
                {
                    b.HasOne("BC7.Domain.UserMultiAccount", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId");

                    b.HasOne("BC7.Domain.UserAccountData", "UserAccountData")
                        .WithMany("UserMultiAccounts")
                        .HasForeignKey("UserAccountDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Z.EntityFramework.Plus.AuditEntryProperty", b =>
                {
                    b.HasOne("Z.EntityFramework.Plus.AuditEntry", "Parent")
                        .WithMany("Properties")
                        .HasForeignKey("AuditEntryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
